sudo: required

language: python

services:
  - docker

before_install:
- docker pull biosustain/cobra-notebook
- docker ps -a

script:
- docker run -v $TRAVIS_BUILD_DIR:/tmp/notebooks biosustain/cobra-notebook /bin/sh -c "pip install runipy && cd /tmp/notebooks && ./test_notebooks.sh"