sudo: required

language: python
python:
  - 2.7
  - 3.4

services:
  - docker

before_install:
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- docker pull biosustain/cameo-wercker-box

script:
- docker run biosustain/cameo-wercker-box /bin/bash -c "source activate cameo$TRAVIS_PYTHON_VERSION && pip install runipy cameo[all] && cd /tmp/notebooks && ./test_notebooks.sh"
