sudo: required

language: python

services:
  - docker

before_install:
- docker pull biosustain/cobra-notebook
- docker ps -a

script:
- docker run -v $TRAVIS_BUILD_DIR:/tmp/notebooks biosustain/cobra-notebook /bin/sh -c "pip install runipy && runipy /tmp/notebooks/01-quick-start.ipynb"