sudo: required

language: python

services:
  - docker

before_install:
- docker pull biosustain/cobra-notebook
- docker ps -a

script:
- docker run biosustain/cobra-notebook /bin/sh -c "pip install runipy && runipy 01-quick-start.ipynb"