sudo: required

language: python

env:
  - CONDAENV=python2.7
  - CONDAENV=python3.4
  - CONDAENV=python

services:
  - docker

before_install:
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- docker pull biosustain/cobra-cplex

script:
- docker run -v $(pwd):/tmp/notebooks biosustain/cobra-cplex /bin/bash -c "source activate $CONDAENV && pip install cameo --upgrade && cd /tmp/notebooks && ./test_notebooks.sh"


