sudo: required

language: python

env:
  - CONDAENV=python2 # python 2.7
  - CONDAENV=python3.4

services:
  - docker

before_install:
- docker login -e=$DOCKER_EMAIL -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
- docker pull biosustain/cobra-cplex

script:
- docker run -v $(pwd):/tmp/notebooks biosustain/cobra-cplex /bin/bash -c \
  "jupyter nbextension enable --py --sys-prefix widgetsnbextension &&
  source activate $CONDAENV &&
  pip install cameo --upgrade &&
  cd /tmp/notebooks &&
  ./test_notebooks.sh"


